const CardData = [
    {
        id: 1,
        imgsrc: "images/image1.jpg",
        Heading: "FalconSat#1",
        Lyear: "2006",
        Slaunch: "False",
        Slanding: "launch_landing",
    },
    {
        id: 2,
        imgsrc: "images/image2.jpg",
        Heading: "DemoFalconSat#2",
        Lyear: "launch_year",
        Slaunch: "launch_success",
        Slanding: "launch_landing",
    },
    {
        id: 3,
        imgsrc: "images/image3.jpg",
        Heading: "Trailblazer#3",
        Lyear: "launch_year",
        Slaunch: "launch_success",
        Slanding: "launch_landing",
    },
    {
        id: 4,
        imgsrc: "images/image4.jpg",
        Heading: "Ratsat#4",
        Lyear: "launch_year",
        Slaunch: "launch_success",
        Slanding: "launch_landing",
    },
    {
        id: 5,
        imgsrc: "images/image5.jpg",
        Heading: "{misson_name}#",
        Lyear: "launch_year",
        Slaunch: "launch_success",
        Slanding: "launch_landing",
    },
    {
        id: 6,
        imgsrc: "images/image6.jpg",
        Heading: "{misson_name}#",
        Lyear: "launch_year",
        Slaunch: "launch_success",
        Slanding: "launch_landing",
    },
    {
        id: 7,
        imgsrc: "images/image7.jpg",
        Heading: "{misson_name}#",
        Lyear: "launch_year",
        Slaunch: "launch_success",
        Slanding: "launch_landing",
    },
    {
        id: 8,
        imgsrc: "images/image8.jpg",
        Heading: "{misson_name}#",
        Lyear: "launch_year",
        Slaunch: "launch_success",
        Slanding: "launch_landing",
    },
]
export default CardData;